## Dataframes

In [2]:
import pandas as pd
import numpy as np

Un dataframe es una estructura de datos bidimensional para almacenar información en pandas

### Crear un Dataframe

Desde un diccionario

In [7]:
datos = { 'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta'], 'Edad': [28, 34, 29, 42], 'Sexo': ['F', 'M', 'M', 'F'] }
df = pd.DataFrame(datos)
df

   Nombre  Edad Sexo
0     Ana    28    F
1    Luis    34    M
2  Carlos    29    M
3   Marta    42    F

Desde un array de numpy

In [ ]:
array = np.random.randn(10, 5) # Crear un array NumPy de 10 filas y 5 columnas con valores aleatorios
df = pd.DataFrame(array, columns=['A', 'B', 'C', 'D', 'E']) # Crear un DataFrame a partir del array con nombres de columnas
df.head(3) # Muestra las primeras 3 filas del DataFrame

          A         B         C         D         E
0 -1.647531 -0.062716 -0.600540 -1.426379 -0.377997
1  0.778151  0.539654 -2.067867  0.092758 -0.016002
2  0.932167  0.514665 -2.155252 -1.864337  0.153766

Desde un archivo CSV

In [10]:
!dir

 El volumen de la unidad C no tiene etiqueta.
 El n�mero de serie del volumen es: 9ABB-90BD

 Directorio de c:\Users\Fran\Documents\EOI2025\06_IA\Curso_Python_IA_nov25\pandas

27/01/2026  08:18    <DIR>          .
26/01/2026  13:13    <DIR>          ..
27/01/2026  08:28             6.148 datafrane.ipynb
27/01/2026  08:17            17.256 series.ipynb
               2 archivos         23.404 bytes
               2 dirs   5.926.817.792 bytes libres

In [11]:
df = pd.read_csv('../ficheros/datos_ficticios.csv', header='infer')  # Cargar un DataFrame desde un archivo CSV, inferiendo los nombres de las columnas
df.head(3)  # Muestra las primeras 3 filas del DataFrame

,nombre,direccion,correo_electronico,telefono
0,Severiano Muro-Berrocal,"Via de Morena Gonzalo 286, Albacete, 11846",manuelavila@example.org,+34942 546 574
1,Inocencio Salmerón Alfaro,"Cañada de Gaspar Arjona 37, Huelva, 13528",eutropio59@example.com,+34826 14 02 72
2,Alicia Anita Jimenez Taboada,"C. de Chelo Téllez 7, Valladolid, 40342",berta08@example.com,+34 881 969 129

Chequeo de algunos atributos del Dataframe

In [12]:
df.shape  # Obtener la forma del DataFrame (número de filas y columnas)

(1000, 4)

In [13]:
df.size  # Obtener el número total de elementos en el DataFrame

4000

In [14]:
df.ndim  # Obtener el número de dimensiones del DataFrame

2

In [15]:
df.columns  # Obtener los nombres de las columnas del DataFrame

Index(['nombre', 'direccion', 'correo_electronico', 'telefono'], dtype='object')

In [16]:
df.index  # Obtener los índices del DataFrame

RangeIndex(start=0, stop=1000, step=1)

In [18]:
type(df)

pandas.core.frame.DataFrame

Estadísticas del Dataframe

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nombre              1000 non-null   object
 1   direccion           1000 non-null   object
 2   correo_electronico  1000 non-null   object
 3   telefono            1000 non-null   object
dtypes: object(4)
memory usage: 31.4+ KB

In [20]:
df.describe()  # Obtener estadísticas descriptivas del DataFrame

,nombre,direccion,correo_electronico,telefono
count,1000,1000,1000,1000
unique,1000,1000,1000,1000
top,Severiano Muro-Berrocal,"Via de Morena Gonzalo 286, Albacete, 11846",manuelavila@example.org,+34942 546 574
freq,1,1,1,1

Mostrar la cabeza y la cola de un Dataframe

In [21]:
df.head()  # Muestra las primeras 5 filas del DataFrame

,nombre,direccion,correo_electronico,telefono
0,Severiano Muro-Berrocal,"Via de Morena Gonzalo 286, Albacete, 11846",manuelavila@example.org,+34942 546 574
1,Inocencio Salmerón Alfaro,"Cañada de Gaspar Arjona 37, Huelva, 13528",eutropio59@example.com,+34826 14 02 72
2,Alicia Anita Jimenez Taboada,"C. de Chelo Téllez 7, Valladolid, 40342",berta08@example.com,+34 881 969 129
3,Azahara Parejo Barranco,"Avenida de Jose Ramón Pablo 8 Apt. 97 , Soria,...",jimenamorera@example.com,+34885 113 193
4,Graciano Peral Villena,"Acceso Amparo Pallarès 10, Santa Cruz de Tener...",luisina18@example.net,+34 971 233 069

In [22]:
df.tail()  # Muestra las últimas 5 filas del DataFrame

,nombre,direccion,correo_electronico,telefono
995,Rosalina Galván Alfonso,"Callejón Teodora Montaña 45, Girona, 07009",porfiriosans@example.net,+34 975205192
996,Consuelo del Vergara,"Avenida de Ángeles Menéndez 45 Puerta 4 , Sala...",leivasabina@example.org,+34876 465 287
997,Valentina Ricart Rosselló,"Cuesta Heriberto Novoa 78 Piso 6 , León, 48428",moreno66@example.org,+34 723 047 023
998,Néstor Naranjo,"Acceso Mariano Plaza 83, Asturias, 10890",florentino41@example.net,+34883 70 00 56
999,Catalina Medina-Coello,"Pasaje de Sarita Seguí 3 Apt. 72 , Cantabria, ...",hferrer@example.com,+34978439333

In [23]:
df.columns = ['name','direction','mail','phone']
df.head()  # Muestra las primeras 5 filas del DataFrame con los nuevos nombres de columnas

,name,direction,mail,phone
0,Severiano Muro-Berrocal,"Via de Morena Gonzalo 286, Albacete, 11846",manuelavila@example.org,+34942 546 574
1,Inocencio Salmerón Alfaro,"Cañada de Gaspar Arjona 37, Huelva, 13528",eutropio59@example.com,+34826 14 02 72
2,Alicia Anita Jimenez Taboada,"C. de Chelo Téllez 7, Valladolid, 40342",berta08@example.com,+34 881 969 129
3,Azahara Parejo Barranco,"Avenida de Jose Ramón Pablo 8 Apt. 97 , Soria,...",jimenamorera@example.com,+34885 113 193
4,Graciano Peral Villena,"Acceso Amparo Pallarès 10, Santa Cruz de Tener...",luisina18@example.net,+34 971 233 069

In [26]:
#df.name  # Acceder a la columna 'name' del DataFrame
df['name']  # Acceder a la columna 'name' del DataFrame

0           Severiano Muro-Berrocal
1         Inocencio Salmerón Alfaro
2      Alicia Anita Jimenez Taboada
3           Azahara Parejo Barranco
4            Graciano Peral Villena
                   ...
995         Rosalina Galván Alfonso
996            Consuelo del Vergara
997       Valentina Ricart Rosselló
998                  Néstor Naranjo
999          Catalina Medina-Coello
Name: name, Length: 1000, dtype: object

In [27]:
type(df['name'])

pandas.core.series.Series

In [30]:
df_nombre = df[['name']]  # Asignar la columna 'name' a una nueva variable
df_nombre

                             name
0         Severiano Muro-Berrocal
1       Inocencio Salmerón Alfaro
2    Alicia Anita Jimenez Taboada
3         Azahara Parejo Barranco
4          Graciano Peral Villena
..                            ...
995       Rosalina Galván Alfonso
996          Consuelo del Vergara
997     Valentina Ricart Rosselló
998                Néstor Naranjo
999        Catalina Medina-Coello

[1000 rows x 1 columns]

In [31]:
type(df_nombre)

pandas.core.frame.DataFrame

In [32]:
df_nombre_mail = df[['name', 'mail']]  # Asignar las columnas 'name' y 'mail' a una nueva variable
df_nombre_mail

                             name                      mail
0         Severiano Muro-Berrocal   manuelavila@example.org
1       Inocencio Salmerón Alfaro    eutropio59@example.com
2    Alicia Anita Jimenez Taboada       berta08@example.com
3         Azahara Parejo Barranco  jimenamorera@example.com
4          Graciano Peral Villena     luisina18@example.net
..                            ...                       ...
995       Rosalina Galván Alfonso  porfiriosans@example.net
996          Consuelo del Vergara   leivasabina@example.org
997     Valentina Ricart Rosselló      moreno66@example.org
998                Néstor Naranjo  florentino41@example.net
999        Catalina Medina-Coello       hferrer@example.com

[1000 rows x 2 columns]

In [34]:
df_nombre_mail2 = df.loc[:100, ['name', 'mail']]  # Otra forma de asignar las columnas 'name' y 'mail' a una nueva variable
df_nombre_mail2

                             name                           mail
0         Severiano Muro-Berrocal        manuelavila@example.org
1       Inocencio Salmerón Alfaro         eutropio59@example.com
2    Alicia Anita Jimenez Taboada            berta08@example.com
3         Azahara Parejo Barranco       jimenamorera@example.com
4          Graciano Peral Villena          luisina18@example.net
..                            ...                            ...
96          Gracia Batlle Pinilla  zacariasfernandez@example.net
97                 Jafet de Ramis              zraya@example.net
98     María José Feliu Castañeda     huguettrinidad@example.com
99              Desiderio del Mas  apolinarmontalban@example.net
100              Camilo Amor Grau         lucioroman@example.com

[101 rows x 2 columns]

In [35]:
df_propio = df.iloc[:100,[0,1,3]] # me quedo con las 100 primeras filas, y las columas 1,2 y 4
df_propio

,name,direction,phone
0,Severiano Muro-Berrocal,"Via de Morena Gonzalo 286, Albacete, 11846",+34942 546 574
1,Inocencio Salmerón Alfaro,"Cañada de Gaspar Arjona 37, Huelva, 13528",+34826 14 02 72
2,Alicia Anita Jimenez Taboada,"C. de Chelo Téllez 7, Valladolid, 40342",+34 881 969 129
3,Azahara Parejo Barranco,"Avenida de Jose Ramón Pablo 8 Apt. 97 , Soria,...",+34885 113 193
4,Graciano Peral Villena,"Acceso Amparo Pallarès 10, Santa Cruz de Tener...",+34 971 233 069
...,...,...,...
95,Adrián Collado Mateos,"Via de Lola Tomas 95, Guipúzcoa, 09258",+34 920 69 13 35
96,Gracia Batlle Pinilla,"Urbanización Julio Carreras 64, Madrid, 33604",+34900 39 91 19
97,Jafet de Ramis,"Via Brunilda Ramirez 73 Piso 0 , Toledo, 48745",+34 843 77 86 85
98,María José Feliu Castañeda,"Calle María Del Carmen Osorio 94 Piso 9 , Vall...",+34879485562
99,Desiderio del Mas,"Urbanización Vicenta Vilalta 539 Puerta 4 , Te...",+34919 941 503

Quedarme con los datos de una fila

In [ ]:
fila2 = df.iloc[2]  # Acceder a la fila con índice 2
fila2

name                    Alicia Anita Jimenez Taboada
direction    C. de Chelo Téllez 7, Valladolid, 40342
mail                             berta08@example.com
phone                                +34 881 969 129
Name: 2, dtype: object

Borrar las columnas de un Dataframe

Eliminar los datos de una o más columnas pero no realmente sino para utilizarlo en alguna operación

In [39]:
df_propio.drop(columns=['direction','phone'])  # Eliminar las columnas 'direction' y 'phone' del DataFrame df_propio

                            name
0        Severiano Muro-Berrocal
1      Inocencio Salmerón Alfaro
2   Alicia Anita Jimenez Taboada
3        Azahara Parejo Barranco
4         Graciano Peral Villena
..                           ...
95         Adrián Collado Mateos
96         Gracia Batlle Pinilla
97                Jafet de Ramis
98    María José Feliu Castañeda
99             Desiderio del Mas

[100 rows x 1 columns]

In [41]:
df_propio

,name,direction,phone
0,Severiano Muro-Berrocal,"Via de Morena Gonzalo 286, Albacete, 11846",+34942 546 574
1,Inocencio Salmerón Alfaro,"Cañada de Gaspar Arjona 37, Huelva, 13528",+34826 14 02 72
2,Alicia Anita Jimenez Taboada,"C. de Chelo Téllez 7, Valladolid, 40342",+34 881 969 129
3,Azahara Parejo Barranco,"Avenida de Jose Ramón Pablo 8 Apt. 97 , Soria,...",+34885 113 193
4,Graciano Peral Villena,"Acceso Amparo Pallarès 10, Santa Cruz de Tener...",+34 971 233 069
...,...,...,...
95,Adrián Collado Mateos,"Via de Lola Tomas 95, Guipúzcoa, 09258",+34 920 69 13 35
96,Gracia Batlle Pinilla,"Urbanización Julio Carreras 64, Madrid, 33604",+34900 39 91 19
97,Jafet de Ramis,"Via Brunilda Ramirez 73 Piso 0 , Toledo, 48745",+34 843 77 86 85
98,María José Feliu Castañeda,"Calle María Del Carmen Osorio 94 Piso 9 , Vall...",+34879485562
99,Desiderio del Mas,"Urbanización Vicenta Vilalta 539 Puerta 4 , Te...",+34919 941 503

In [42]:
df_propio.drop(columns=['direction','phone'], inplace=True)  # Eliminar las columnas 'direction' y 'phone' del DataFrame df_propio de forma permanente
df_propio

                            name
0        Severiano Muro-Berrocal
1      Inocencio Salmerón Alfaro
2   Alicia Anita Jimenez Taboada
3        Azahara Parejo Barranco
4         Graciano Peral Villena
..                           ...
95         Adrián Collado Mateos
96         Gracia Batlle Pinilla
97                Jafet de Ramis
98    María José Feliu Castañeda
99             Desiderio del Mas

[100 rows x 1 columns]

#### Slicing condicional

In [3]:
df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Lucia'],
    'Edad': [28, 34, 29, 42, 23],
    'Sexo': ['F', 'M', 'M', 'F', 'F'],
    'Altura': [1.65, 1.80, 1.75, 1.60, 1.70],
    'Peso': [60, 80, 75, 55, 65]
})

In [4]:
df.head()

   Nombre  Edad Sexo  Altura  Peso
0     Ana    28    F    1.65    60
1    Luis    34    M    1.80    80
2  Carlos    29    M    1.75    75
3   Marta    42    F    1.60    55
4   Lucia    23    F    1.70    65

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  5 non-null      object
 1   Edad    5 non-null      int64
 2   Sexo    5 non-null      object
 3   Altura  5 non-null      float64
 4   Peso    5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [6]:
df.describe()

            Edad    Altura       Peso
count   5.000000  5.000000   5.000000
mean   31.200000  1.700000  67.000000
std     7.190271  0.079057  10.368221
min    23.000000  1.600000  55.000000
25%    28.000000  1.650000  60.000000
50%    29.000000  1.700000  65.000000
75%    34.000000  1.750000  75.000000
max    42.000000  1.800000  80.000000

In [7]:
df[df['Edad'] > 30]  # Filtrar filas donde la edad es mayor a 30

  Nombre  Edad Sexo  Altura  Peso
1   Luis    34    M     1.8    80
3  Marta    42    F     1.6    55

In [8]:
df[df.Sexo == 'F']  # Filtrar filas donde el sexo es femenino

  Nombre  Edad Sexo  Altura  Peso
0    Ana    28    F    1.65    60
3  Marta    42    F    1.60    55
4  Lucia    23    F    1.70    65

In [ ]:
df[-(df.Sexo == 'F')] # Filtrar filas donde el sexo no es femenino

   Nombre  Edad Sexo  Altura  Peso
1    Luis    34    M    1.80    80
2  Carlos    29    M    1.75    75

In [12]:
df[(df.Sexo == 'M') & (df['Altura'] > 1.75)]  # Filtrar filas donde el sexo es masculino y la altura es mayor a 1.75

  Nombre  Edad Sexo  Altura  Peso
1   Luis    34    M     1.8    80

In [ ]:
df[(df.Altura > 1.70) & (df.Altura < 1.80)]  # Filtrar filas donde la altura está entre 1.70 y 1.80. Condiciones de rango

   Nombre  Edad Sexo  Altura  Peso
2  Carlos    29    M    1.75    75

In [14]:
df[(df.Altura > 1.70) | (df.Sexo == 'F')] # Filtrar filas donde la altura es mayor a 1.70 o el sexo es femenino. Condiciones "o"

   Nombre  Edad Sexo  Altura  Peso
0     Ana    28    F    1.65    60
1    Luis    34    M    1.80    80
2  Carlos    29    M    1.75    75
3   Marta    42    F    1.60    55
4   Lucia    23    F    1.70    65

#### Leer y escribir en Excel

In [15]:
dfx = pd.read_excel('../ficheros/notas.xlsx', sheet_name='Hoja1', header=0)  # Cargar un DataFrame desde un archivo Excel
dfx.head()

    Alumno  Nota Prácticas  Nota Examen  Nota Media
0  Alumno1               2            5         3.5
1  Alumno2               3            7         5.0
2  Alumno3               4            4         4.0
3  Alumno4               2            3         2.5
4  Alumno5               7            9         8.0

In [16]:
dfx.drop(columns=['Nota Media'], inplace=True)  # Eliminar la columna 'Nota Media' del DataFrame dfx de forma permanente
dfx.head()

    Alumno  Nota Prácticas  Nota Examen
0  Alumno1               2            5
1  Alumno2               3            7
2  Alumno3               4            4
3  Alumno4               2            3
4  Alumno5               7            9

In [18]:
dfx.loc[0, 'Alumno'] = 'Fran' # Cambiar el nombre del alumno en la primera fila a 'Fran'
dfx.head()

    Alumno  Nota Prácticas  Nota Examen
0     Fran               2            5
1  Alumno2               3            7
2  Alumno3               4            4
3  Alumno4               2            3
4  Alumno5               7            9

In [19]:
dfx_copia = dfx.copy()  # Crear una copia del DataFrame dfx
dfx_copia

     Alumno  Nota Prácticas  Nota Examen
0      Fran               2            5
1   Alumno2               3            7
2   Alumno3               4            4
3   Alumno4               2            3
4   Alumno5               7            9
5   Alumno6               9            8
6   Alumno7               2            7
7   Alumno8               6            1
8   Alumno9               9            2
9  Alumno10               8            3

In [20]:
dfx_copia2 = dfx[:]
dfx_copia2

     Alumno  Nota Prácticas  Nota Examen
0      Fran               2            5
1   Alumno2               3            7
2   Alumno3               4            4
3   Alumno4               2            3
4   Alumno5               7            9
5   Alumno6               9            8
6   Alumno7               2            7
7   Alumno8               6            1
8   Alumno9               9            2
9  Alumno10               8            3

In [21]:
#dfx.drop(columns=['Nota Prácticas'], inplace=True)  # Eliminar la columna 'Nota Prácticas' del DataFrame dfx
dfx.drop('Nota Prácticas', axis=1, inplace=True) # Eliminar la columna 'Nota Prácticas' del DataFrame dfx

In [22]:
dfx

     Alumno  Nota Examen
0      Fran            5
1   Alumno2            7
2   Alumno3            4
3   Alumno4            3
4   Alumno5            9
5   Alumno6            8
6   Alumno7            7
7   Alumno8            1
8   Alumno9            2
9  Alumno10            3

In [23]:
dfx.drop(5,axis=0,inplace=True) # Eliminar la fila con índice 5 del DataFrame dfx
dfx

     Alumno  Nota Examen
0      Fran            5
1   Alumno2            7
2   Alumno3            4
3   Alumno4            3
4   Alumno5            9
6   Alumno7            7
7   Alumno8            1
8   Alumno9            2
9  Alumno10            3

In [25]:
dfx.reindex(range(len(dfx)))  # Reindexar el DataFrame dfx para que los índices sean consecutivos

    Alumno  Nota Examen
0     Fran          5.0
1  Alumno2          7.0
2  Alumno3          4.0
3  Alumno4          3.0
4  Alumno5          9.0
5      NaN          NaN
6  Alumno7          7.0
7  Alumno8          1.0
8  Alumno9          2.0

In [28]:
#dfx.drop(5, axis=0, inplace=True)
dfx2 = dfx.reindex([0,1,2,3,4,5,6,7])
dfx2

    Alumno  Nota Examen
0     Fran          5.0
1  Alumno2          7.0
2  Alumno3          4.0
3  Alumno4          3.0
4  Alumno5          9.0
5      NaN          NaN
6  Alumno7          7.0
7  Alumno8          1.0

In [29]:
dfx2.drop(5, axis=0, inplace=True)

In [30]:
dfx2

    Alumno  Nota Examen
0     Fran          5.0
1  Alumno2          7.0
2  Alumno3          4.0
3  Alumno4          3.0
4  Alumno5          9.0
6  Alumno7          7.0
7  Alumno8          1.0

In [31]:
dfx2.reset_index(drop=True, inplace=True)  # Reindexar el DataFrame dfx2 para que los índices sean consecutivos
dfx2

    Alumno  Nota Examen
0     Fran          5.0
1  Alumno2          7.0
2  Alumno3          4.0
3  Alumno4          3.0
4  Alumno5          9.0
5  Alumno7          7.0
6  Alumno8          1.0

In [35]:
dataframe_ordenado = dfx2.sort_values(by='Nota Examen',ascending=False)

In [36]:
dataframe_ordenado

    Alumno  Nota Examen
4  Alumno5          9.0
1  Alumno2          7.0
5  Alumno7          7.0
0     Fran          5.0
2  Alumno3          4.0
3  Alumno4          3.0
6  Alumno8          1.0

In [37]:
dfx['Nota Examen'] = dfx['Nota Examen'] * 10 # Multiplicar la columna 'Nota Examen' por 10
dfx.head()

    Alumno  Nota Examen
0     Fran           50
1  Alumno2           70
2  Alumno3           40
3  Alumno4           30
4  Alumno5           90

Añadir columna al Dataframe

In [38]:
df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Lucia'],
    'Edad': [28, 34, 29, 42, 23],
    'Sexo': ['F', 'M', 'M', 'F', 'F'],
    'Altura': [1.65, 1.80, 1.75, 1.60, 1.70],
    'Peso': [60, 80, 75, 55, 65]
})

In [39]:
df.head()

   Nombre  Edad Sexo  Altura  Peso
0     Ana    28    F    1.65    60
1    Luis    34    M    1.80    80
2  Carlos    29    M    1.75    75
3   Marta    42    F    1.60    55
4   Lucia    23    F    1.70    65

In [40]:
df['IMC'] = df['Peso'] / (df['Altura'] ** 2)  # Calcular el Índice de Masa Corporal (IMC) y agregarlo como una nueva columna
df.head()

   Nombre  Edad Sexo  Altura  Peso        IMC
0     Ana    28    F    1.65    60  22.038567
1    Luis    34    M    1.80    80  24.691358
2  Carlos    29    M    1.75    75  24.489796
3   Marta    42    F    1.60    55  21.484375
4   Lucia    23    F    1.70    65  22.491349

Merge

In [41]:
df_2_primeras = df[:2] # Seleccionar las dos primeras filas del DataFrame
df_2_primeras

  Nombre  Edad Sexo  Altura  Peso        IMC
0    Ana    28    F    1.65    60  22.038567
1   Luis    34    M    1.80    80  24.691358

In [42]:
df_2_ultimas = df[-2:] # Seleccionar las dos últimas filas del DataFrame
df_2_ultimas

  Nombre  Edad Sexo  Altura  Peso        IMC
3  Marta    42    F     1.6    55  21.484375
4  Lucia    23    F     1.7    65  22.491349

In [45]:
df_2_ultimas.loc[3, 'Nombre'] = 'Ana'  # Cambiar el nombre en la fila con índice 3 a 'Ana'

In [46]:
df_2_ultimas

  Nombre  Edad Sexo  Altura  Peso        IMC
3    Ana    42    F     1.6    55  21.484375
4  Lucia    23    F     1.7    65  22.491349

In [47]:
union = pd.merge(df_2_primeras, df_2_ultimas, left_on='Nombre', right_on='Nombre', how='inner')  # unir los dos DataFrames seleccionados usando una unión interna
union.head()

,Nombre,Edad_x,Sexo_x,Altura_x,Peso_x,IMC_x,Edad_y,Sexo_y,Altura_y,Peso_y,IMC_y
0,Ana,28,F,1.65,60,22.038567,42,F,1.6,55,21.484375

Concatenar por columnas

In [48]:
concatenado = pd.concat([df_2_primeras, df_2_ultimas], ignore_index=True)  # Concatenar los dos DataFrames seleccionados ignorando los índices originales
concatenado

  Nombre  Edad Sexo  Altura  Peso        IMC
0    Ana    28    F    1.65    60  22.038567
1   Luis    34    M    1.80    80  24.691358
2    Ana    42    F    1.60    55  21.484375
3  Lucia    23    F    1.70    65  22.491349